# Generated by Django 5.2.11 on 2026-02-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('projects', 'Projects'), ('contact', 'Contact')], max_length=50, verbose_name='Page')),
                ('section', models.CharField(choices=[('hero', 'Hero'), ('stats', 'Stats'), ('skills', 'Skills'), ('featured_projects', 'Featured Projects'), ('cta', 'CTA'), ('bio', 'Biography'), ('services', 'Services'), ('timeline', 'Timeline'), ('header', 'Header'), ('footer', 'Footer'), ('custom', 'Custom')], max_length=50, verbose_name='Section')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Title')),
                ('subtitle', models.TextField(blank=True, verbose_name='Subtitle')),
                ('content', models.TextField(blank=True, help_text='Use Markdown for formatting', verbose_name='Content')),
                ('content_html', models.TextField(blank=True, help_text='Raw HTML content', verbose_name='Content HTML')),
                ('image', models.ImageField(blank=True, null=True, upload_to='page_content/', verbose_name='Image')),
                ('icon', models.CharField(blank=True, help_text='SVG icon name', max_length=100, verbose_name='Icon')),
                ('button_text', models.CharField(blank=True, max_length=100, verbose_name='Button Text')),
                ('button_url', models.CharField(blank=True, max_length=200, verbose_name='Button URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Page Content',
                'verbose_name_plural': 'Page Contents',
                'ordering': ['page', 'section', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='MMR Portfolio', max_length=100, verbose_name='Site Name')),
                ('site_description', models.TextField(blank=True, verbose_name='Site Description')),
                ('logo_text', models.CharField(default='MMR', max_length=100, verbose_name='Logo Text')),
                ('hero_title', models.CharField(default='Bonjour, je suis MMR', max_length=200, verbose_name='Hero Title')),
                ('hero_subtitle', models.TextField(default='Je conçois et développe des expériences numériques modernes, performantes et accessibles.', verbose_name='Hero Subtitle')),
                ('hero_cta_text', models.CharField(default='Voir mes projets', max_length=100, verbose_name='Hero CTA Text')),
                ('hero_cta_url', models.CharField(default='/projects/', max_length=200, verbose_name='Hero CTA URL')),
                ('hero_secondary_cta_text', models.CharField(default='Me contacter', max_length=100, verbose_name='Hero Secondary CTA Text')),
                ('hero_secondary_cta_url', models.CharField(default='/contact/', max_length=200, verbose_name='Hero Secondary CTA URL')),
                ('stats_years', models.CharField(default='5+', max_length=50, verbose_name='Years Experience')),
                ('stats_projects', models.CharField(default='50+', max_length=50, verbose_name='Projects Count')),
                ('stats_clients', models.CharField(default='30+', max_length=50, verbose_name='Clients Count')),
                ('stats_passion', models.CharField(default='100%', max_length=50, verbose_name='Passion Text')),
                ('cta_title', models.CharField(default='Prêt à démarrer votre projet ?', max_length=200, verbose_name='CTA Title')),
                ('cta_subtitle', models.TextField(default='Discutons de votre projet et transformons vos idées en réalité numérique.', verbose_name='CTA Subtitle')),
                ('cta_button_text', models.CharField(default='Me contacter', max_length=100, verbose_name='CTA Button Text')),
                ('cta_button_url', models.CharField(default='/contact/', max_length=200, verbose_name='CTA Button URL')),
                ('footer_text', models.TextField(blank=True, verbose_name='Footer Text')),
                ('footer_copyright', models.CharField(default='© 2024 MMR Portfolio. Tous droits réservés.', max_length=200, verbose_name='Copyright')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Contact Email')),
                ('contact_location', models.CharField(default='Paris, France', max_length=100, verbose_name='Location')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
