# Generated by Django 5.2.11 on 2026-02-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_sociallink_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='icon',
            field=models.TextField(help_text='Code svg (taille 24)', verbose_name='Icon Class'),
        ),
    ]
