# Generated by Django 5.2.11 on 2026-02-13 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_sociallink_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.CharField(blank=True, max_length=200, verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='project',
            name='completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Completion Date'),
        ),
        migrations.AddField(
            model_name='project',
            name='duration',
            field=models.CharField(blank=True, max_length=100, verbose_name='Duration'),
        ),
        migrations.AddField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Featured'),
        ),
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.CharField(blank=True, max_length=200, verbose_name='Role'),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='Short Description'),
        ),
        migrations.CreateModel(
            name='ProjectSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('features', 'Features'), ('challenges', 'Challenges'), ('lessons_learned', 'Lessons Learned'), ('objectives', 'Objectives'), ('results', 'Results'), ('testimonials', 'Testimonials'), ('gallery', 'Gallery'), ('custom', 'Custom')], max_length=50, verbose_name='Section Type')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Title')),
                ('subtitle', models.TextField(blank=True, verbose_name='Subtitle')),
                ('content', models.TextField(blank=True, help_text='Use Markdown for formatting', verbose_name='Content')),
                ('content_html', models.TextField(blank=True, verbose_name='Content HTML')),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_sections/', verbose_name='Image')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='Icon')),
                ('button_text', models.CharField(blank=True, max_length=100, verbose_name='Button Text')),
                ('button_url', models.CharField(blank=True, max_length=200, verbose_name='Button URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='main.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project Section',
                'verbose_name_plural': 'Project Sections',
                'ordering': ['project', 'order'],
            },
        ),
    ]
