# Generated by Django 5.2.11 on 2026-02-13 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_project_client_project_completion_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectSection',
        ),
    ]
